<?php

namespace BlogBundle\Repository;

/**
 * SignalementComRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SignalementComRepository extends \Doctrine\ORM\EntityRepository
{
}
