<?php

namespace BlogBundle\Repository;

/**
 * SignalementArtRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SignalementArtRepository extends \Doctrine\ORM\EntityRepository
{
}
