BlogBundle\Entity\Role:
    type: entity
    table: null
    repositoryClass: BlogBundle\Repository\RoleRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        role:
            type: string
            length: '15'
            unique: true

    manyToMany:
        users:
            targetEntity: User
            mappedBy: roles

    lifecycleCallbacks: {  }
