BlogBundle\Entity\SignalementArt:
    type: entity
    table: null
    repositoryClass: BlogBundle\Repository\SignalementArtRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        creationdt:
            type: datetime

    manyToOne:
        user:
            targetEntity: User
            inversedBy: signalements_art
        article:
            targetEntity: Article
            inversedBy: signalements

    lifecycleCallbacks: {  }
