BlogBundle\Entity\Theme:
    type: entity
    table: null
    repositoryClass: BlogBundle\Repository\ThemeRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        theme:
            type: string
            length: 255
            unique: true

    manyToMany:
        articles:
            targetEntity: Article
            mappedBy: themes

    lifecycleCallbacks: {  }
