BlogBundle\Entity\User:
    type: entity
    table: null
    repositoryClass: BlogBundle\Repository\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        username:
            type: string
            length: '20'
            unique: true
        password:
            type: string
            length: '20'
        nom:
            type: string
            length: '20'
        prenom:
            type: string
            length: '20'
        mail:
            type: string
            length: '50'

    manyToMany:
        roles:
            targetEntity: Role
            inversedBy: users

    oneToMany:
        articles:
            targetEntity: Article
            mappedBy: user

    oneToMany:
        commentaires:
            targetEntity: Commentaire
            mappedBy: user

    oneToMany:
        signalements_com:
            targetEntity: SignalementCom
            mappedBy: user

    oneToMany:
        signalements_art:
            targetEntity: SignalementArt
            mappedBy: user

    lifecycleCallbacks: {  }
